[meta]
seed = 42 # random seed
use_amp = true 
num_workers = 8
pin_memory = true 
num_epochs = 200
batch_size = 128
samplerate = 32000

clean_data_dirname = "/home/lizhinan/project/dataset/dns_fullband/datasets/clean_32k"
noisy_data_dirname = "/home/lizhinan/project/dataset/dns_fullband/datasets/noisy_32k"
#noise_data_dirname = "/home/lizhinan/project/dataset/dns_fullband/datasets/noise_32k"

# set experiment dir.
save_model_dir = "/home/lizhinan/project/lightse/DTLNPytorch/models"
experiment_name = "DTLN_0603_npu_nonorm"

# set preload model
preload_model_path = ""
[audio]
samplerate = 32000
duration = 10


[model]
path = "modules.dtlnModel_rk_npu_nonorm.Pytorch_DTLN_stateful"
[model.args]
frameLength = 1024
hopLength = 256
# seperation kernel config
hidden_size = 128
encoder_size = 256

[loss]
method = "dtln-snr"
#method = "MSE+dtln-snr"


[optimizer]
lr = 0.002
weight_decay = 1e-9

[trainer]
path = "modules.trainer.Trainer"
[trainer.args]
clip_grad_norm_ornot = true
clip_grad_norm_value = 3